common/modules/shop/models/Product.php
<?php

namespace common\modules\shop\models;
use yii\db\ActiveRecord;
use Yii;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "shop_product".
 *
 * @property integer $id
 * @property integer $category_id
 * @property string $price
 * @property string $created_at
 * @property string $updated_at
 *
 * @property ShopCategory $category
 */
class Product extends ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'shop_product';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['category_id', 'price'], 'required'],
            [['category_id'], 'integer'],
            [['price'], 'number'],
            [['image'], 'safe'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('shop', 'ID'),
            'category_id' => Yii::t('shop', 'Category'),
            'price' => Yii::t('shop', 'Price'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCategory()
    {
        return $this->hasOne(Category::className(), ['id' => 'category_id']);
    }

    /**
     * @inheritdoc
     * @return ProductQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new ProductQuery(get_called_class());
    }
    
    public function getImageUrl() {
        return strlen($this->image) ? Yii::$app->getModule('shop')->imagesUrl.'/'.$this->image : false;
    }
    
    public function getCategoryOptions() {
        return ArrayHelper::map(Category::find()->all(), 'id', 'title'); 
    }
}

common/modules/shop/controllers/CatalogController.php
<?php

namespace common\modules\shop\controllers;

use Yii;
use common\modules\shop\models\Product;
use common\modules\shop\models\ProductSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * ProductController implements the CRUD actions for Product model.
 */
class CatalogController extends Controller
{
    
    public function behaviors()
    {
        return [
            'access' => [
                'class' => \yii\filters\AccessControl::className(),
                'rules' => [
                    // allow authenticated users
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    
                ],
            ],
        ];
    }

    public function actionIndex() {
        
        $searchModel = new ProductSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }
    
}

common/modules/shop/views/catalog/_item.php
<?php

/* 
 * Copyright (C) 2015 Vladislav Waxme
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

use yii\helpers\Html;

if (!$src = $model->imageUrl) {
    $src = "http://placehold.it/150x150";
}

?>
<div class="col-lg-3 col-md-4 col-sm-6 col-xs-12">
    <div class="thumbnail">
      <img src="<?=$src?>" alt="<?php echo $model->category->title; ?>">
      <div class="caption text-center">
        <h3><?php echo $model->category->title;?></h3>
        <p>₪&nbsp;<?php echo sprintf("%d", $model->price)?></p>
        <p>
            <a href="#" class="btn btn-primary" role="button">
                <?php echo Html::encode(Yii::t('shop', 'Add to cart'));?>
            </a> 
        </p>
      </div>
    </div>
</div>

common/modules/shop/views/catalog/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\modules\shop\models\ProductSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="product-search">

    <?php $form = ActiveForm::begin([
        'action' => "",
        'method' => 'get',
        'options' => [
            'name' => 'productSearchForm',
        ],
    ]); ?>

    <?= $form->field($model, 'category_id')->dropDownList($model->categoryOptions, [
        'class' => 'form-control',
        'prompt' => Yii::t('shop', 'All Categories'),
        'onchange' => 'document.forms.productSearchForm.submit()',
    ]) ?>

<!--
    <div class="form-group">
        <?= Html::submitButton(Yii::t('shop', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('shop', 'Reset'), ['class' => 'btn btn-default']) ?>
    </div>
-->

    <?php ActiveForm::end(); ?>

</div>

common/modules/shop/views/catalog/index.php
<?php

use yii\helpers\Html;
use yii\widgets\ListView;

/* @var $this yii\web\View */
/* @var $searchModel common\modules\shop\models\CategorySearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('shop', 'Catalog');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="product-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <?php echo $this->render('_search', ['model' => $searchModel]); ?>
    <div class="row">
        <?= ListView::widget([
            'dataProvider' => $dataProvider,
            'itemOptions' => ['class' => 'item'],
            'itemView' => function ($model, $key, $index, $widget) {
                return $this->render('_item', [
                    'model' => $model,
                    'key' => $key,
                    'index' => $index,
                    'widget' => $widget,
                ]);
            },
        ]) ?>
    </div>
    
</div>